### ISSUE TITLE
Unify types of sequences in datasets

### ISSUE THREAD

**Issue by adamjanovsky** [crocs-muni/sec-certs#112]
Often, types of sequences (mostly lists and sets) are used interchangeably throughout the project. E.g., consider `heuristics.cpe_matches` of `CommonCriteriaCert` and `FIPSCertificate`. We should unify (or even enforce) how this objects are being handled. 

Special care must be taken when (de)serializing.

**Comment by J08nY** [comment]
I will also say that this is causing me issues on the website side of things. I am taking these serializable objects and doing `to_dict` to them to obtain a representation that I am then diffing against their representation taken from the database (to see whether they changed and whether we should notify subscribers of changes). However, I am observing very high rates of "change" events that are not really change events, just non-determinism in array ordering in what should really be a set.

Part of the blame is on my side of things as to get a "pure" dictionary out of a `ComplexSerializable` object I am recursively walking its `to_dict` and applying transformations and one of these turns a set into a list, thus introducing part of the non-determinism.

However, I think a good solution goes deeper. I think having a "recursive" variant of the `to_dict` method on the `ComplexSerializable` type that gives a canonical/deterministic (and JSON-safe) dictionary representation of the object and its contained objects, would be quite great and not that much work. I think I can just fix my function to be deterministic, test it a bit and upstream it into the tool itself.

**Comment by adamjanovsky** [comment]
@J08nY should we settle on some coordinated progress on this or did you resorted to treating it yourself in the end? I was thinking of getting together for 30 minutes and writing down what we should do. This is the last "refactoring" issue that we currently have and honestly, I would need more input from your side for successful resolution.

**Comment by J08nY** [comment]
> However, you proposed some recursive to_dict methods that I don't understand at the moment :).

Just to explain this a bit, the current `to_dict`   only serializes the object it is applied on and keeps other ComplexSerializableTypes in the resulting dict intact. Then the `to_json` processes those recursively and does the full serialization. That is all that I was talking about and it is somehow orthogonal to the serialization issues mentioned.

However, one more issue that I had to resolve at some point is that of serialization of hashable types into non-hashable dicts. What happened when I was hand rolling serialization was that I had several levels of serialization and one level still had sets but did not have ComplexSerializableTypes which lead to an issue if at the level above a ComplexSerializableType object was in a set as its serialized dict was not hashable.

Anyway we can have the discussion and try to resolve the serialization systematically.
