### ISSUE TITLE
Unify FIPS and CC identification.

### ISSUE THREAD

**Issue by J08nY** [crocs-muni/sec-certs#125]
Currently a FIPS certificate has
 - `cert_id` that is a string type (in JSON) but that really represents the integer certificate number.
 - `dgst` that is equal to the `cert_id` above.
However, a CC certificate has no `cert_id` (only an id in heuristics, as there is no guaranteed certificate ID present for CC).
A CC certificate also has a `dgst` that is a hash of some fields of the certificate that will hopefully not change. The `dgst` is
a 16 character hex string.

I propose the following:
 - Change the FIPS `cert_id` type to integer in the serialized JSON.
 - Change the FIPS `dgst` to also be a 16 character hex digest of the hash of the `cert_id` for example, so that this field is unified in the two datasets.

I need this because:
 - I am using the `cert_id` field in the seccerts.org page and a sort on a string field containing numbers is just wrong.
 - I am using the `dgst` field in the seccerts.org page and having it formatted differently for FIPS/CC causes issues.

**Comment by adamjanovsky** [comment]
sounds good. Though we'll loose some readability for the FIPS dgsts. But that's acceptable I guess

**Comment by J08nY** [comment]
W.r.t readability, the data has both the dgst and cert_id so its just a different attribute to display. The site will have both dgst and cert_id based links, so hopefully no issues there.

**Comment by J08nY** [comment]
Ugh, this is going to be harder to do than I thought, in the FIPS code `cert.dgst` and `cert.cert_id` are used quite interchangably as they were thought to be always equal so now its a mix. I will try to work out a solution.
