### ISSUE TITLE
Fix broken PP IDs parsing

### ISSUE THREAD

**Issue by adamjanovsky** [crocs-muni/sec-certs#129]
While PPs are parsed from statically downloaded files, PP IDs are not properly processed and matched to certificates.

**Comment by adamjanovsky** [comment]
Turns out to be already fixed for a while...

**Comment by J08nY** [comment]
This does not seem to be fixed as I am still getting `"pp_ids": null` in the processed CC data. Should I manually supply some PP dataset to the tool for the linking to work or something?

**Comment by adamjanovsky** [comment]
Hm, I see. The CLI does not invoke processing of PPs implicitly. I added explicit call into `build` action of CLI. I see the PP IDs correctly processed after manually invoking

```python
dset = CCDataset({}, Path("./debug_dataset"), "cc_full_dataset", "sample dataset description")
dset.get_certs_from_web(to_download=True)
dset.process_protection_profiles()
dset.to_json(dset.json_path)
```

relevant part in the json then looks like

```
"protection_profiles": [
    {
        "_type": "ProtectionProfile",
        "pp_name": "Enterprise Security Management - Policy Management Version 2.1",
        "pp_link": "https://www.commoncriteriaportal.org/files/ppfiles/pp_esm_pm_v2.1.pdf",
        "pp_ids": [
            "PP_ESM_PM_V2.1"
        ]
    }
```

@J08nY if this is the output that you expect, just click merge on #162 please.
