### ISSUE TITLE
Include search for specific APDU commands in documentation 

### ISSUE THREAD

**Issue by petrs** [crocs-muni/sec-certs#14]
Commands to obtain get proprietary chip info etc.
List of regular expressions are here:
https://github.com/petrs/pyAPDUFuzzer/commit/3cccb8ff72bf24cb20eb50208e45e563dff90a29
https://github.com/petrs/pyAPDUFuzzer/commit/d31dbd52a1833916d50ae678ca2fe101d0ada77e
https://github.com/petrs/pyAPDUFuzzer/commit/54f2060b85ba8dd398e1cc385d443b2b455113e7

**Comment by adamjanovsky** [comment]
Won't be implemented, see https://github.com/crocs-muni/sec-certs/pull/224#issuecomment-1141907860
