### ISSUE TITLE
Functionality: detect possibly vulnerable certificates by shared terms in certificate(s)

### ISSUE THREAD

**Issue by petrs** [crocs-muni/sec-certs#147]
Example use-case: estID, ROCA and ID 163484 eIDAS memo. The memo referenced vulnerable chips, but a different ones than used in estID cards.  

Idea:
- input: list of known vulnerable certificates
- generate --find-affecting graph
- find term(s) shared by all known vulnerable certificates in their --find-affecting graphs
- generate graph with potentially affected certificates for these terms using --find-affected
-

**Comment by adamjanovsky** [comment]
This description is slightly confusing, but note that exactly this is addressed by #180.
