### ISSUE TITLE
Resolve set (de)serialization

### ISSUE THREAD

**Issue by adamjanovsky** [crocs-muni/sec-certs#169]
Currently, sets that undergo process of serialization are sorted and converted to list during that process. Yet, when deserializing from JSON, they are kept as lists (as there is no way to tell whether these were originally lists or sets). 

We should (de)serialize sets as `ComplexSerializableType` to fix this, but it will create some backward compatibility problems, especially w.r.t. webpage. 

@J08nY will you survive this change? :)

**Comment by adamjanovsky** [comment]
Fix is super simple, in encoder, do

```python
        if isinstance(obj, set):
            return {"_type": "Set", "elements": sorted(list(obj))}
```

in object hook of decoder, do:

```python
        if "_type" in obj and obj["_type"] == "Set":
            return set(obj["elements"])
```

**Comment by J08nY** [comment]
This only affects `to_json` and `from_json` right? If so, I don't mind because I only do stuff with `to_dict` and `from_dict` and have my own set de/serialization for MongoDB based on a similar method.
