### ISSUE TITLE
Certificate ID lost

### ISSUE THREAD

**Issue by J08nY** [crocs-muni/sec-certs#174]
It seems that with the change that added normalization of cert IDs that landed in #166 there is at least
one certificate that has lost its cert ID value: https://seccerts.org/cc/08b09322ee9df0af/

Before it had:

    "cert_id": "2012-4-INF-1418",
    ...
    "rules_cert_id": { "2012-4-INF-1418": 1},

Then it was updated to:

    "cert_id": null,
    ...
    "rules_cert_id": {
        "2012-4-INF-1418": 1,
        "2012-4-INF-1418 v1": 1
    },

Also during processing the following issue appeared:

    "errors": [
      "Failed to read metadata of certs/reports/pdf/08b09322ee9df0af.pdf, error: \u0027NoneType\u0027 object has no attribute \u0027items\u0027",
      "Failed to read metadata of certs/reports/pdf/08b09322ee9df0af.pdf, error: \u0027NoneType\u0027 object has no attribute \u0027items\u0027"
    ],

**Comment by adamjanovsky** [comment]
@GeorgeFI can you take a look at it?
