### ISSUE TITLE
Add timeout for pdftotext

### ISSUE THREAD

**Issue by adamjanovsky** [crocs-muni/sec-certs#175]
@J08nY, can you confirm that this run completely failed because of `pdftotext` timing out? I'm surprised that single timeout crashes the whole tool. Will fix if you confirm. Shouldn't be difficult to create Timeouts for functions processed in parallel.

**Comment by J08nY** [comment]
It seems like it did, but this happened during the server outage in which affected the run in weird ways so maybe adding stuff to the tool to handle this is premature, the whole server was doing weird things.

**Comment by J08nY** [comment]
Closing this as it had more to do with the poor state of the server than the tool.
