### ISSUE TITLE
Investigate  best pdf to txt conversion options

### ISSUE THREAD

**Issue by adamjanovsky** [crocs-muni/sec-certs#185]
Historically, all pdf files were converted to text by calling `pdftotext` entry point of `poppler-utils` package (on Linux). This was (#183) replaced with [a pdftotext library](https://pypi.org/project/pdftotext/) that leveraged poppler API without a need to call `subprocess.open("pdftotext")`. 

Still, there is some parametrization that needs to be experimented with and settled. As conversion happen quite early in the pipeline, its quality can have paramount consequences on the final results. 

While [pdftotext library](https://pypi.org/project/pdftotext/) allows three different settings of `Raw` and `Physical` parameters, there are some other options directly in the `pdftotext` entry point that could possibly improve the quality of the conversion. 

Also, if some visually alligned choice is to be made, spaces need to get stripped before RE processing.

Note that `poppler-utils` must be installed to run `pdftotext` CLI.

**Comment by adamjanovsky** [comment]
See #194

**Comment by petrs** [comment]
@adamjanovsky resolution is Raw=True for now. With the following additional steps possible (already done in version 1):
1. Try to convert from pdf to txt with Raw=True
2. Test how many spaces are in the resulting text document. If about half of file length (meaning that there is extra space after every character) => convert with Raw=False
 
Some documents (in order of tens) have some sub-parts converted properly with Raw=True while other parts only with Raw=False. For now, we do not try to correct such files and process them with Raw=True completely (as they will not be captured by the condition 2.)
