### ISSUE TITLE
Compute highest level of SAR, SFR claimed, display with text information on web

### ISSUE THREAD

**Issue by petrs** [crocs-muni/sec-certs#200]
Use extracted SAR and SFR claims, heuristically establish the likely achieved value (highest) and visually display (e.g., within the minimum and maximum range levels).

Example:
https://seccerts.org/cc/861434b03ddcac64/
Security target
Security Assurance Requirements (SAR)
ADV_FSP.5

**Comment by adamjanovsky** [comment]
@petrs From where should these be collected? Technically, they can appear at multiple places:

- Security target keywords
- Certification report keywords
- In the linked protection profiles. For instance, some certificate links to a protection profile for which we have a processed sample in `pp_dataset.json`. That PP can also list SARs that need to be parsed on their own... 
- Directly in the `security_level` field parsed from csv, e.g.,

```json
"security_level": {
                "_type": "Set",
                "elements": [
                    "ALC_FLR.3",
                    "EAL3"
                ]
},
```.

If there's a conflict in the SARs, how should the conflict be resolved?
