### ISSUE TITLE
Generate pdf with graph subcomponents

### ISSUE THREAD

**Issue by petrs** [crocs-muni/sec-certs#22]

**Comment by adamjanovsky** [comment]
@petrs Any idea what you meant by this issue? I'll probably close this unless it's really related to our current state of art.

**Comment by petrs** [comment]
@adamjanovsky This was meant to generate multiple pdf files instead of single one with all cert_ids (which is large and messy). But is only of potential use, no priority

**Comment by adamjanovsky** [comment]
Graphs are not interactive on web or can be rendered on-demand in notebooks. Closing this as won't fix.
