### ISSUE TITLE
Add more variety to cert rules

### ISSUE THREAD

**Issue by J08nY** [crocs-muni/sec-certs#223]
Some ideas below:

## More device IDs
Maybe STM stuff, maybe ARM chip IDs?

## More crypto algs
Go through competitions and more weird algos:
 - AES candidates: http://competitions.cr.yp.to/aes.html
 - SHA3 competition: https://www.nist.gov/programs-projects/cryptographic-hash-algorithm-competition
 - PHC: https://www.password-hashing.net/
 - LWC: https://csrc.nist.gov/Projects/Lightweight-Cryptography
 - PQC: https://csrc.nist.gov/projects/post-quantum-cryptography
 - eSTREAM: http://competitions.cr.yp.to/estream.html
 - CAESAR: http://competitions.cr.yp.to/caesar.html

## More vendors and evaluation facilities
We have very few, there is definitely more, from the non-smartcard world for example.

https://www.commoncriteriaportal.org/labs/

## TEE-related stuff
TrustZone, SGX, etc.

## Improve the cert-id matching
Go through certificates that do not have an ID assigned to them and make or change a rule to match,
more normalization of the cert ID might be necessary.

**Comment by adamjanovsky** [comment]
Not sure here, @J08nY, do you consider this thing resolved with #224 or do you want to continue? If yes, close it please.

**Comment by J08nY** [comment]
This is fixed with #224, apart from the improved cert ID matching, which however is a long term goal separate from this issue.
