### ISSUE TITLE
seccerts.org/docs returns 404

### ISSUE THREAD

**Issue by adamjanovsky** [crocs-muni/sec-certs#228]
@J08nY could we please set `.htaccess` of webpage to redirect from `/url` to `/url.html` or something like that? Ideally, we  want to redirect both variants: `/docs/` and `/docs`, I think...

On few places I have these urls and they return 404 currently. In case you don't want to do it fore some reason, just tell me and I'll try to fix the links instead.

**Comment by J08nY** [comment]
Fixed. Hope I didn't introduce a path traversal vulnerability with this :joy:.

**Comment by J08nY** [comment]
So it seems that by fixing this I messed up the docs upload. Undoing and reopening.

**Comment by J08nY** [comment]
Fixed via  209279b.
