### ISSUE TITLE
Display cleaned extracted SARs on web

### ISSUE THREAD

**Issue by adamjanovsky** [crocs-muni/sec-certs#235]
Given a certificate, we currently show SARs extracted from pdfs on the web. These are slightly unreliable and should be ideally replaced with SARs processed by [SARTransformer](https://github.com/crocs-muni/sec-certs/blob/main/sec_certs/model/sar_transformer.py). These SARs reside in `CCHeuristics.extracted_sars` variable. 

https://github.com/crocs-muni/sec-certs/blob/299c02136a303c49b6f2cf03423332125a9a8f62/sec_certs/sample/common_criteria.py#L307

@J08nY, could we please display these SARs instead of those extracted from pdfs?

I think that displaying them in "Heuristics Summary" at the top of the page would be just fine.

**Comment by J08nY** [comment]
Btw. do we also do something for SFRs?
