### ISSUE TITLE
Dockerize web app to allow for local deployments

### ISSUE THREAD

**Issue by adamjanovsky** [crocs-muni/sec-certs#241]
**Is your feature request related to a problem? Please describe.**

Currently, the webpage is manually deploit. Eventhough the deployment process is carefully documented, we should strive for fully automatic deployment of the webpage from two different reasons:

1. To allow quick redeployment in case when we loose the data x years from now when having little time to work on this project.
2. To allow custom deployment of our users. This is applicable especially when the users aim to connect our database with their internal sources that are potentially confidential. While the webpage is not necessary to run our toolchain, it provides a lot of usability. 

**Describe the solution you'd like**

- Prepare a Docker file (or Docker compose file) that deploys the whole seccerts.org webpage
- Adjust configuration so that some components (e.g. docs, label-studio, ...) can be turned off to allow for localhost deployments

**Describe alternatives you've considered**

Didn't really consider any.

**Comment by J08nY** [comment]
Partially done via 9fc0c77eeb9260ebd8bcf0899349f120e90976a9.
