### ISSUE TITLE
Detect re-certification

### ISSUE THREAD

**Issue by J08nY** [crocs-muni/sec-certs#256]
We could detect when a certificate is a re-certification as many such cases include the same wording, which in case of BSI is:
 - `This is a re-certification based on BSI-DSZ-CC-0417-2008.`
 - `a re-certification based on the certificate BSI-DSZ-CC-0171-2002`

Other schemes have similar wording in certification reports.

**Comment by adamjanovsky** [comment]
Just bumped into this. This will be implemented as a by-product of https://github.com/crocs-muni/sec-certs/pull/322
