### ISSUE TITLE
Link certificate's identified Protection Profile to URL with its description (web presentation)

### ISSUE THREAD

**Issue by petrs** [crocs-muni/sec-certs#265]
**Is your feature request related to a problem? Please describe.**
Can't click directly on the identified protection profile to get more information
**Describe the solution you'd like**
add hyperlink to source pp document (e.g., PP_APP_v1.3 -> https://www.commoncriteriaportal.org/files/ppfiles/PP_APP_v1.3.pdf) 

**Additional context**

**Comment by J08nY** [comment]
This is already implemented for the identified protection profiles, see:
https://seccerts.org/cc/fac3224e68f630d8/
and 
https://seccerts.org/pp/cca277256af66a9993e8/.

We can't do that for stuff where we don't have the protection profile but just the ID.
