### ISSUE TITLE
Rename CommonCriteria files -> cc

### ISSUE THREAD

**Issue by adamjanovsky** [crocs-muni/sec-certs#287]
Filenames of `common_criteria*.py` should be renamed to `cc*.py`.

@J08nY Would you like to rename also classes? E.g. `CommonCriteriaCert` to `CCCertificate`? We're not consistent there as well.

**Comment by adamjanovsky** [comment]
@J08nY what do you think about `CommonCriteriaCert` -> `CCCertificate`? Three `C`s in a row seem a lot :D But we have `CCDataset`, `FIPSDataset`, `FIPSCertificate`, and then we have `CommonCriteriaCert` ...

**Comment by J08nY** [comment]
Go for it.
> Special cases aren't special enough to break the rules.
- Zen of Python

**Comment by adamjanovsky** [comment]
PEP 8 strikes back 😆 

> [A Foolish Consistency is the Hobgoblin of Little Minds](https://peps.python.org/pep-0008/#a-foolish-consistency-is-the-hobgoblin-of-little-minds)

**Comment by J08nY** [comment]
I would still go for it CCCertificate is not unreadable I think.
