### ISSUE TITLE
OCR processing fails

### ISSUE THREAD

**Issue by dmacko232** [crocs-muni/sec-certs#298]
When ocr is used to convert pdf to text it fails with error message 
`Error during OCR of, using garbage: invalid literal for int() with base 10: 'mpzvoklker/image-06'`

The issue is most likely caused by wrong slicing of string (`fname[6:-4]` instead of` fname[-6:-4]`)
https://github.com/crocs-muni/sec-certs/blob/9d1d44d04532609524fd862697179e179a6ea92c/src/sec_certs/utils/pdf.py#L64

**Comment by J08nY** [comment]
I do not have time to fix this. `fname[-6:-4]` is likely wrong as well as triple-digit pagecounts are reasonable. Better do a split on the `"-"` and the `"."`.

**Comment by adamjanovsky** [comment]
I drafted a fix:

https://github.com/crocs-muni/sec-certs/pull/299/files#diff-868e915618fb558aec444f32bf8f70056ffe499f0cb2f71c6d9fa75a4cacc005

works on my machine :)
