### ISSUE TITLE
Replace subprocess.call in OCR with pytesseract library

### ISSUE THREAD

**Issue by adamjanovsky** [crocs-muni/sec-certs#335]
As we generally try to avoid `subprocess.run()`, it would be good idea to replace the OCR-related calls with a [Python wrapper for tesseract](https://pypi.org/project/pytesseract/). 

This concerns refactoring the following snippet

https://github.com/crocs-muni/sec-certs/blob/b808490207666abf0e4afc97305d05ca9facc0fa/src/sec_certs/utils/pdf.py#L40-L70

@J08nY just for your reference

**Comment by GeorgeFI** [comment]
@adamjanovsky Hi, I am taking this one, because I think it should be low hanging fruit, therefore I can continue on other issues afterwards.

**Comment by J08nY** [comment]
This is done via #357
