### ISSUE TITLE
delete old-api branch

### ISSUE THREAD

**Issue by adamjanovsky** [crocs-muni/sec-certs#402]
The old api-branch is likely not going to be ever used in the project.

@petrs if you want, could you please fork the repo and make some kind of backup of the branch? Subsequently, could you please delete the `old-api` branch from this repository?

**Comment by adamjanovsky** [comment]
@petrs Just FYI, I will delete the branch in two weeks unless something happens here.

**Comment by J08nY** [comment]
This is done right? I see not `old-api` here.
