### ISSUE TITLE
CI/CD: Publish package to PyPi on release

### ISSUE THREAD

**Issue by adamjanovsky** [crocs-muni/sec-certs#47]
- [ ] On release (alternatively on push to master, but we would need to create `dev` branch then) GitHub action or Travis CI/CD should be triggered that will publish the current version of the tool to PyPi, so that it can be installed with `pip install sec-certs`
- [ ] Add relevant badges (e.g. see https://thomas-cokelaer.info/blog/2014/08/1013/) to the readme

Some relevant information can be found at: 
- https://docs.github.com/en/actions/guides/building-and-testing-python
- https://packaging.python.org/tutorials/packaging-projects/

**Comment by J08nY** [comment]
This needs someone to be the owner of the package on PyPi and to generate the access token needed for the package upload. @adamjanovsky @petrs  Who should that be?

**Comment by adamjanovsky** [comment]
> This needs someone to be the owner of the package on PyPi and to generate the access token needed for the package upload. @adamjanovsky @petrs Who should that be?

That would presumably be me. @KeleranV please get in touch in this regard once necessary.
