### ISSUE TITLE
Refactoring: Split large files that cover multiple classes

### ISSUE THREAD

**Issue by adamjanovsky** [crocs-muni/sec-certs#51]
We should probably split gigantic files `dataset.py` and `certificate.py` into multiple files, one file per class.

**Comment by J08nY** [comment]
Sure, make a `dataset` or `certificate` package and create the split files there. Or do it the other way around and have a `fips` and `cc` package and have the `dataset.py` and `certificate.py` files there.

**Comment by adamjanovsky** [comment]
Yep, probably `dataset` and `certificate` packages, since we're introducing new datasets `CVEDataset`, `CPEDataset`, ...

**Comment by adamjanovsky** [comment]
Closed with #59
