### ISSUE TITLE
Introduce SimpleComplexSerializableType

### ISSUE THREAD

**Issue by adamjanovsky** [crocs-muni/sec-certs#54]
Since `ComplexSerializableType` is an abstract type, all child classes must implement methods `to_dict()` and `from_dict()`. But most of the child classes only define these as

```
def to_dict(self):
    return copy.deepcopy(self.__dict__)

@classmethod
def from_dict(cls, dct: Dict):
    return cls(*tuple(dct.values()))
```

it would thus be benefitial to create a `SimpleComplexSerializableType` that implements these and let other classes inherit from this one. Would save many LoC.

Also, a default `to_json()` and `from_json()` implementation should be introduced.

**Comment by J08nY** [comment]
Is the name `SimpleComplexSerializableType` really a good one?  <s>simple</s> + <s>complex</s> serializable type = serializable type :grin:.

**Comment by adamjanovsky** [comment]
Well, the naming is unfortunate, I'll adjust that :))
