### ISSUE TITLE
Docker: Add the ability to export experimental results out of docker

### ISSUE THREAD

**Issue by adamjanovsky** [crocs-muni/sec-certs#63]
As @KeleranV pointed on today's call, the current problem with Docker is that while the `cc_oop_demo.py` script runs flawlessly, the Dataset files, jsons, etc., they remain trapped inside the Docker image :). 

As of now, the Python script is parametrized by a single local path parameter, where all results are stored. This will remain true even when replaced by full-experiment script in the future. Thus, we should decide on how to make the experiment results accessible outside of the docker for someone who uses Docker.

We discussed today with @KeleranV that he will investigate the options and pick some suitable one. @J08nY, do you have any opinion on this?

**Comment by J08nY** [comment]
There are several ways of sharing stuff between the docker container and the host, see https://www.digitalocean.com/community/tutorials/how-to-share-data-between-the-docker-container-and-the-host. We should pick one that makes the most sense and go with it.

**Comment by KeleranV** [comment]
According to what I've seen, we will need the files contained in the `sec-certs/examples/debug_dataset` directory, so I think that sharing this specific folder should be enough, a line like `docker run sec-certs:latest -v ~/processed_data:/opt/sec-certs/examples/debug_dataset` should do the trick

**Comment by adamjanovsky** [comment]
sounds good 👍 , `-v` could be mistaken with verbose, so we should add the long tag `--volume` to readme.
