### ISSUE TITLE
Fix PyPi package

### ISSUE THREAD

**Issue by adamjanovsky** [crocs-muni/sec-certs#67]
It seems that whatever is being pushed to PyPi repository, is not working. To be exact, running

```
pip3 install -e .
process-certs
```
works as expected, so the local install is ok. However, trying

```
pip3 install -U sec-certs
process-certs
```
exits with the following error:

```
Traceback (most recent call last):
  File "/Users/adam/.pyenv/versions/3.8.1/bin/process-certs", line 5, in <module>
    from process_certificates import main
ModuleNotFoundError: No module named 'process_certificates'
```

we should fix the PyPi package.

**Comment by J08nY** [comment]
Well @adamjanovsky this is the result of keeping the scripts out of the package directory (which I think was your idea :grin: ). The top-level scripts need to be moved into the package directory.

**Comment by adamjanovsky** [comment]
> Well @adamjanovsky this is the result of keeping the scripts out of the package directory (which I think was your idea 😁 ). The top-level scripts need to be moved into the package directory.

What's the difference between local pip install and PyPi install then? Shouldn't be any, right?

**Comment by J08nY** [comment]
The difference is that the non-local install is installed from a dist package (wheel, sources, whatever) which only includes some files and not the whole repository. In setuptools this is controlled by the `MANIFEST` file and the `packages` argument and some other keyword arguments to the setup call. You can include the top-level scripts in the dist but I would consider it bad practice and it is not done often. Packages just have scripts in them and provide entry-points that run them.

**Comment by adamjanovsky** [comment]
Kk, my point was to avoid putting the entry points immediately next to the source files. I'm for creating some folder `entrypoints` inside the sec-certs package.
