### ISSUE TITLE
Add mechanism for publishing latest CC, FIPS dataset on web

### ISSUE THREAD

**Issue by adamjanovsky** [crocs-muni/sec-certs#77]
We should add some mechanism that will allow the administrators of the project publish new versions of the JSON datasets for other researchers to download on seccerts.org. This can be done:
- manually
- through some web interface

the `CCDataset` now implements method `CCDataset.from_web_latest()` that should fetch the latest dataset published by us into an object. This is handy especially when working with some notebooks, as any researcher can write

```python
dset = CCDataset.from_web_latest()
df = dset.to_pandas()
```

and obtain table representation of the dataset that he can easily experiment with, draw plots, etc. The method `from_web_latest()` references static url address where the latest dataset should always sit.

**Comment by J08nY** [comment]
This will soon be live on:
 - https://seccerts.org/cc/dataset.json
 - https://seccerts.org/fips/dataset.json

Updated daily.

**Comment by adamjanovsky** [comment]
Great, I have a request then. Once published on seccerts, could you please edit the fields `fips_latest_snapshot`, `cc_latest_snapshot` in https://github.com/crocs-muni/sec-certs/blob/dev/sec_certs/config/settings.yaml to point to these urls?

Also, since we have like zero backward compatilibity, I'm thinking whether seccerts should not periodically pull from master for example and produce these datasets on those versions? I'm not certain what would it mean for you though, if it's feasible at all. The idea is that I sometimes fix random bugs and would like to update the `from_web_latest()` datasets. But they would keep being produced by the old versions. Not to prompt you to update manually, automatic updates could be a way to go?

**Comment by J08nY** [comment]
Automatic updates are a possibility although I am unsure how to handle them as the update tasks (and the workers they are performed in) are spawned in an uWSGI server instance that is continuously running and thus I am unsure if updating the `sec_certs` package underneath that will work. Maybe some dirty Python reimport trick could do the job. Or maybe just restarting/reloading the uWSGI server and celery instance. Hmm. I will definitely have a look at that.

**Comment by adamjanovsky** [comment]
I see. I dont have the knowledge of how the infrastructure is organized. Would the `sec_certs` be installed with `pip -e`, it really could suffice just to pull latest version and `importlib.reload(sec_certs)`.

**Comment by J08nY** [comment]
I am unsure whether `importlib.reload` would do the right thing. Also there are multiple processes involved:
 - uWSGI workers which serve the Flask app. To do so they load data from MongoDB and mostly do not import from `sec_certs` but just present the data without loading it into Certificate objects. They also schedule Celery background tasks (if someone registers for a subscription for example, the confirmation email is sent in the background).
 - Celery workers which do the tasks and work mostly with `sec_certs` package: e.g. update data and stuff it into MongoDB, send notifications, ...

An "autoupdate" mechanism would need to:
 1. Pull in the latest version of `sec-certs`, which would be easy, with an editable install (`pip -e .`) it would just be one git pull from the repo.
 2. Seamlessly reload the version of the sec-certs package in all of the running worker processes. This is harder than the first step.. It could be done via a simple shell script that sends a HUP signal to the uWSGI and Celery master processes maybe, but I am unsure if that will be seamless and actually reload the code on the Celery side.

**Comment by adamjanovsky** [comment]
I see. We can ignore the auto update for now and only implement it if we find out we really need it?
